config/routes.rb
Rails.application.routes.draw do

  resources :posts
  get 'friends/index'
  delete 'friends/destroy'


  resources :friend_requests, :except => [:show, :edit]

  devise_for :users
  resources :users, :only => [:show, :edit]

  devise_scope :user do
    authenticated  do
      root to: 'posts#index', as: 'authenticated_user_root'
    end
    unauthenticated do
      root to: 'devise/sessions#new', as: 'unauthenticated_user_root'
    end
  end

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
    <% if user_signed_in? %>
      <%= link_to "Gregersen Social", authenticated_user_root_path, class: 'navbar-brand' %>
    <% else %>
      <%= link_to "Gregersen Social", unauthenticated_user_root_path, class: 'navbar-brand'  %>
    <% end %>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"> <%= link_to "Randomlink", "#" %></li>
      <li><a href="#">Page 1</a></li>
      <li><a href="#">Page 2</a></li>
      <li><a href="#">Page 3</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <%= render 'layouts/notifications' %>
      <li><a href="<%= edit_user_path(current_user) %>"><%= current_user.email %></a></li>
      <li> <%= link_to 'Logout', destroy_user_session_path, method: 'delete'  %> </li>
    </ul>
  </div>
</nav>

app/views/layouts/_notifications.html.erb
  <button class="btn btn-primary" type="button" id="friendsNotification" data-toggle="dropdown" aria-expanded="true">
  <i class="fa fa-bell">
  <% if @incoming.count > 0  %>
  <div class="true"><%= @incoming.count %></div>
  <% end %>
  </i>
	</button>
  <ul class="dropdown-menu">
  	<li> <%= link_to "View all friends", friends_index_path  %> </li>
    <% @incoming.each do |friendrequest| %>
      <li><%= friendrequest.user_id %></li>
      <% # Indsæt en linje for at hente gravatar/avatar fra friendrequest(anden parten) %>
      <%= link_to "Accept", friend_request_path(friendrequest.id), method: 'patch', remote: true %>
      <%= link_to "Decline", friend_request_path(friendrequest.id), method: 'delete', remote: true %>
    <% end %>
    <li><a href="#">JavaScript</a></li>
  </ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GregSocial</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<% if user_signed_in? %>
	<%= render 'layouts/navbar' %>
<% end %>

<section class="container">

	<%= render 'layouts/messages' %>

	<%= yield %>

</section>

<footer>

</footer>

</body>
</html>